### ISSUE TITLE
데이터 수집 관련 문의

### ISSUE THREAD

**Issue by sam351** [corazzon/COVID-19-eda#1]
안녕하세요! 흥미로운 데이터 분석 공유해주셔서 감사합니다.
다름이 아니라 06-seoul-covid-19-eda.ipynb 에서 covid-19-seoul.csv 데이터를 사용하고 계신데, 코멘트에 언급하신 링크에 들어가도 해당 데이터를 다운로드할 수 있는 곳은 보이지 않는 것 같습니다. 혹시 covid-19-seoul.csv  테이블은 일일히 크롤링하신 건가요?

**Comment by corazzon** [comment]
안녕하세요. 서울시에서 공개한 사이트를 크롤링했습니다. 
5번 파일이 크롤링 파일이고요. 이 이슈를 보고 데이터도 함께 커밋했습니다.
해당 사이트를 크롤링 한지 한 달 정도 되었는데 사이트가 자주 변경되어서 여러 번 코드를 바꿨어요.
그래서 시점에 따라 동작하지 않을 수도 있습니다.
오늘자 크롤링 파일은 covid-19-seoul.csv 이름으로 올려두었어요.

**Comment by sam351** [comment]
5번 크롤링 소스와 csv 데이터 확인했습니다!
감사합니다 :)
